-- CONSULTA COM GROUP BY/HAVING --
-- PROJETA O NOME DAS PESSOAS QUE TEM MAIS DE UMA GANGUE
SELECT NOME_PESSOA AS TRAIDORES
FROM MEMBRO
GROUP BY NOME_PESSOA
HAVING COUNT(NOME_GANGUE) > 1;

-- CONSULTA COM INNER JOIN --
-- PROJETA O PROTAGONISTA, SUAS MISSÕES, RECOMPENSAS E QUAL VEICULO FOI USADO NELAS
SELECT M.NOME_PROTAGONISTA AS PROTAGONISTA, M.DESCRICAO, M.RECOMPENSA, D.NOME_VEICULO AS VEICULO
FROM MISSAO M
INNER JOIN DIRIGE D ON D.NOME_PROTAGONISTA = M.NOME_PROTAGONISTA AND D.DESCRICAO = M.DESCRICAO;

-- CONSULTA COM OUTER JOIN --
-- PROJETA O NOME DAS PESSOAS QUE NÃO PERTENCEM A NENHUMA GANGUE
SELECT P.NOME
FROM PESSOA P
LEFT OUTER JOIN MEMBRO M
ON P.NOME = M.NOME_PESSOA
WHERE M.NOME_GANGUE IS NULL;

-- CONSULTA COM SEMI JUNÇÃO --
-- PROJETA OS NOMES E A MARCA DOS VEÍCULOS QUE TOCAM ALGUMA MÚSICA
SELECT V.NOME, V.MARCA
FROM VEICULO V
WHERE EXISTS (
    SELECT *
    FROM TOCA T
    WHERE T.NOME_VEICULO = V.NOME);

-- CONSULTA COM ANTI-JOIN --
-- PROJETA OS NOMES DOS NPCS QUE NÃO FORAM MORTOS POR NENHUM PROTAGONISTA
SELECT N.NOME
FROM NPC N
WHERE NOT EXISTS (
    SELECT *
    FROM MATA M
    WHERE M.NOME_NPC = N.NOME);

-- SUBCONSULTA DO TIPO ESCALAR --
-- PROJETA A MISSÃO COM A MAIOR RECOMPENSA
SELECT DESCRICAO, RECOMPENSA
FROM MISSAO
WHERE RECOMPENSA = (
    SELECT MAX(RECOMPENSA)
    FROM MISSAO);

-- SUBCONSULTA DO TIPO LINHA -- 
-- PROJETA OS NOMES DOS VEÍCULOS QUE TOCAM A MESMA MUSICA NA MESMA RÁDIO QUE UM VEÍCULO DETERMINADO
SELECT NOME_VEICULO AS VEICULO
FROM TOCA
WHERE (NOME_MUSICA, NOME_RADIO) =
      (SELECT NOME_MUSICA, NOME_RADIO
       FROM TOCA
       WHERE NOME_VEICULO = 'Infernus'
       FETCH FIRST 1 ROW ONLY);

-- SUBCONSULTA DO TIPO TABELA --
-- PROJETA OS NOMES DOS PROTAGONISTAS QUE DIRIGEM OS VEÍCULOS QUE TOCAM DETERMINADA MÚSICA
SELECT DISTINCT NOME_PROTAGONISTA AS PROTAGONISTA
FROM DIRIGE
WHERE NOME_VEICULO IN (
    SELECT NOME_VEICULO
    FROM TOCA
    WHERE NOME_MUSICA = 'Hellraiser');

-- OPERAÇÃO DE CONJUNTO --
-- PROJETA OS NOMES DOS NPCS QUE JÁ FORAM MORTOS TANTO PELO PROTAGONISTA Claude QUANTO PELO PROTAGONISTA Toni
SELECT NOME_NPC AS NPC
FROM MATA
WHERE NOME_PROTAGONISTA LIKE 'Claude%'
INTERSECT
SELECT NOME_NPC
FROM MATA
WHERE NOME_PROTAGONISTA LIKE 'Toni%';-- PROJETA TODOS OS CARROS QUE O PROTAGONISTA TROCOU DE ESTACAO DE RADIO--
SELECT VEICULO.*
FROM VEICULO
WHERE VEICULO.NOME IN (
	SELECT TOCA.NOME_VEICULO
	FROM TOCA
	GROUP BY TOCA.NOME_VEICULO
	HAVING COUNT(DISTINCT TOCA.NOME_RADIO) > 1
)
