-- Super-entidade
CREATE TABLE PESSOA(
    NOME VARCHAR(20) PRIMARY KEY,
    DT_NASC DATE NOT NULL,
    GENERO VARCHAR(9) NOT NULL,
    END_CIDADE VARCHAR(20) NOT NULL,
    END_BAIRRO VARCHAR(20) NOT NULL
);

-- Sub-entidades
CREATE TABLE PROTAGONISTA(
    NOME VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME) REFERENCES PESSOA(NOME)

);

CREATE TABLE NPC(
    NOME VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME) REFERENCES PESSOA(NOME)
);
-- ----------------------------------------------

-- Entidade fraca
CREATE TABLE MISSAO(
    NOME_PROTAGONISTA VARCHAR(20),
    DESCRICAO VARCHAR(100),
    RECOMPENSA NUMERIC(10,2),
    PRIMARY KEY (NOME_PROTAGONISTA, DESCRICAO),
    FOREIGN KEY (NOME_PROTAGONISTA) REFERENCES PROTAGONISTA(NOME)
);
-- ----------------------------------------------

-- Entidades regulares

CREATE TABLE GANGUE(
    NOME VARCHAR(20) PRIMARY KEY,
    COR VARCHAR(20) NOT NULL
);

CREATE TABLE VEICULO(
    NOME VARCHAR(20) PRIMARY KEY,
    MARCA VARCHAR(20),
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE RADIO(
    NOME VARCHAR(30) PRIMARY KEY,
    NUMERO NUMERIC(4,1)
);

CREATE TABLE MUSICA(
    NOME VARCHAR(50) PRIMARY KEY,
    GENERO1 VARCHAR(20) NOT NULL,
    GENERO2 VARCHAR(20)
);

CREATE TABLE ROTINA(
    DESCRICAO VARCHAR(100) PRIMARY KEY,
    NOME_NPC VARCHAR(20) UNIQUE NOT NULL,
    FOREIGN KEY (NOME_NPC) REFERENCES NPC(NOME)
);
-- ----------------------------------------------

-- Entidade associativa
-- É o relacionamento identificador/entidade fraca: MISSAO
-- ----------------------------------------------

-- Auto-relacionamento
CREATE TABLE AJUDA(
    AJUDANTE VARCHAR(20),
    AJUDADO VARCHAR(20),
    PRIMARY KEY (AJUDANTE, AJUDADO),
    FOREIGN KEY (AJUDANTE) REFERENCES PROTAGONISTA(NOME),
    FOREIGN KEY (AJUDADO) REFERENCES PROTAGONISTA(NOME)
);
-- ----------------------------------------------

-- Relacionamentos
CREATE TABLE MEMBRO(
    NOME_PESSOA VARCHAR(20),
    NOME_GANGUE VARCHAR(20),
    PRIMARY KEY (NOME_PESSOA, NOME_GANGUE),
    FOREIGN KEY (NOME_PESSOA) REFERENCES PESSOA(NOME),
    FOREIGN KEY (NOME_GANGUE) REFERENCES GANGUE(NOME)
);

CREATE TABLE MATA(
    NOME_PROTAGONISTA VARCHAR(20),
    NOME_NPC VARCHAR(20),
    KILL_COUNT INTEGER,
    PRIMARY KEY (NOME_PROTAGONISTA, NOME_NPC, KILL_COUNT),
    FOREIGN KEY (NOME_PROTAGONISTA) REFERENCES PROTAGONISTA(NOME),
    FOREIGN KEY (NOME_NPC) REFERENCES NPC(NOME)
);

CREATE TABLE DIRIGE(
    NOME_PROTAGONISTA VARCHAR(20),
    DESCRICAO VARCHAR(100),
    NOME_VEICULO VARCHAR(20),
    PRIMARY KEY (NOME_PROTAGONISTA, DESCRICAO, NOME_VEICULO),
    FOREIGN KEY (NOME_PROTAGONISTA,DESCRICAO) REFERENCES MISSAO(NOME_PROTAGONISTA,DESCRICAO),
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME)
);

-- Ternario
CREATE TABLE TOCA(
    NOME_VEICULO VARCHAR(20),
    NOME_MUSICA VARCHAR(50),
    NOME_RADIO VARCHAR(20) NOT NULL,
    PRIMARY KEY(NOME_VEICULO, NOME_MUSICA),
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME),
    FOREIGN KEY (NOME_MUSICA) REFERENCES MUSICA(NOME),
    FOREIGN KEY (NOME_RADIO) REFERENCES RADIO(NOME)
);
-- ----------------------------------------------